### processing_functions

Functions made to combine spreadsheets to a clear, organised, standard format.

In [17]:
import pandas as pd

In [18]:
paired_bets_file = 'file path.../Paired\ Bets.csv'
paired_bets_file = paired_bets_file.replace("\\", "")
paired_bets = pd.read_csv(paired_bets_file)

paired_bets

,ProfitID,StatusId,Status,BetTypeID,BetType,sportID,sport,SourceID,Source,MarketID,Market,Market1,EventTime,Event,BetOutcome,ExpectedProfitAve,ActualProfit,Note,datecreated
0,7967346,1,Unsettled,2,Free (SNR),2,Football,1,Odds,1,Win,Win,19/11/2019 19:45:00,Wales v Hungary,Hungary,15.910,0.0,NaN,19/11/2019 14:39:18
1,7967454,1,Unsettled,1,Normal,2,Football,1,Odds,1,Win,Win,19/11/2019 19:45:00,North Macedonia v Israel,North Macedonia,-0.335,0.0,NaN,19/11/2019 14:56:02
2,7975857,1,Unsettled,2,Free (SNR),2,Football,1,Odds,2,CS,CS,20/11/2019 19:45:00,Lincoln v Ipswich,1-2,15.090,0.0,NaN,20/11/2019 14:13:10
3,7979780,1,Unsettled,1,Normal,2,Football,1,Odds,1,Win,Win,22/11/2019 20:00:00,Levante v Mallorca,Levante,-0.360,0.0,NaN,20/11/2019 22:11:55
4,7979843,1,Unsettled,2,Free (SNR),1,Horse Racing,1,Odds,5,Win,Win,21/11/2019 14:05:00,Market Rasen 14:05,Buster Valentine,22.330,0.0,"odds changed in smarkets, liability was 118,\n...",20/11/2019 22:20:56
5,7987409,1,Unsettled,1,Normal,2,Football,1,Odds,1,Win,Win,22/11/2019 20:00:00,Levante v Mallorca,Levante,-1.065,0.0,NaN,21/11/2019 21:24:34
6,7998004,1,Unsettled,2,Free (SNR),2,Football,1,Odds,1,Win,Win,23/11/2019 12:30:00,West Ham v Tottenham,Draw,21.475,0.0,NaN,22/11/2019 22:16:02
7,8018379,1,Unsettled,2,Free (SNR),2,Football,1,Odds,2,CS,CS,24/11/2019 16:30:00,Sheff Utd v Man Utd,1-1,21.325,0.0,NaN,24/11/2019 09:55:09

In [19]:
individual_bets_file = 'file path.../Individual\ Bets.csv'
individual_bets_file = individual_bets_file.replace("\\", "")
individual_bets = pd.read_csv(individual_bets_file)

individual_bets

,profitid,ItemID,BookieID,bookiename,BetOutcomeID,BetOutcome,BettingTypeID,bettingtype,Outcome,stake,Odds,commission,liability,return,profit
0,7967346,17692115,32,Coral,0,NaN,1,Back,Hungary,20.00,6.50,0,0.00,110.00,15.92
1,7967346,17692116,100,Smarkets,0,NaN,2,Lay,Hungary,16.22,6.80,2,94.08,15.90,15.90
2,7967454,17692346,45,Skybet,0,NaN,1,Back,North Macedonia,5.00,2.40,0,0.00,7.00,-0.33
3,7967454,17692347,100,Smarkets,0,NaN,2,Lay,North Macedonia,4.76,2.54,2,7.33,4.66,-0.34
4,7975857,17709999,45,Skybet,0,NaN,1,Back,1-2,20.00,11.00,0,0.00,200.00,15.08
5,7975857,17710000,100,Smarkets,0,NaN,2,Lay,1-2,15.41,13.00,2,184.92,15.10,15.10
6,7979780,17718327,2,William Hill,0,NaN,1,Back,Levante,10.00,1.85,0,0.00,8.50,-0.36
7,7979780,17718328,100,Smarkets,0,NaN,2,Lay,Levante,9.84,1.90,2,8.86,9.64,-0.36
8,7979843,17718474,2,William Hill,0,NaN,1,Back,Buster Valentine,30.00,6.00,0,0.00,150.00,22.32
9,7979843,17718475,100,Smarkets,0,NaN,2,Lay,Buster Valentine,22.80,6.60,2,127.68,22.34,22.34
10,7987409,17733575,99,BetWay,0,NaN,1,Back,Levante,30.00,1.87,0,0.00,26.10,-1.07
11,7987409,17733576,100,Smarkets,0,NaN,2,Lay,Levante,29.53,1.92,2,27.17,28.94,-1.06
12,7998004,17754995,99,BetWay,0,NaN,1,Back,Draw,30.00,4.20,0,0.00,96.00,21.47
13,7998004,17754996,100,Smarkets,0,NaN,2,Lay,Draw,21.92,4.40,2,74.53,21.48,21.48
14,8018379,17802309,4,Betfred,0,NaN,1,Back,1-1,30.00,6.50,0,0.00,165.00,21.32
15,8018379,17802310,100,Smarkets,0,NaN,2,Lay,1-1,21.77,7.60,2,143.68,21.33,21.33

The following functions are used for combining the paired and individual bet spreadsheets.

In [20]:
def remove_wanted_columns(spreadsheet):
    """Removes unwanted columns from a preprocessed individual bets spreadsheet."""
    
    spreadsheet.drop(['BookieID', 'BetOutcomeID', 'BettingTypeID', 'ItemID'], 
                     axis=1, inplace=True)
    
    return spreadsheet

individual_bets = remove_wanted_columns(individual_bets)

individual_bets.head(2)

,profitid,bookiename,BetOutcome,bettingtype,Outcome,stake,Odds,commission,liability,return,profit
0,7967346,Coral,NaN,Back,Hungary,20.00,6.5,0,0.00,110.0,15.92
1,7967346,Smarkets,NaN,Lay,Hungary,16.22,6.8,2,94.08,15.9,15.90

In [21]:
def tidy_profit_id(spreadsheet):
    """Renames preprocessed individual bets spreadsheets' profitid to ProfitID.
       This allowed paired and individual bets to be merged on ProfitID."""
    
    spreadsheet.rename(columns={'profitid':'ProfitID'}, inplace=True)
    
    return spreadsheet
    
individual_bets = tidy_profit_id(individual_bets)

individual_bets.head(2)

,ProfitID,bookiename,BetOutcome,bettingtype,Outcome,stake,Odds,commission,liability,return,profit
0,7967346,Coral,NaN,Back,Hungary,20.00,6.5,0,0.00,110.0,15.92
1,7967346,Smarkets,NaN,Lay,Hungary,16.22,6.8,2,94.08,15.9,15.90

In [22]:
def merge_on_profit_id(individual_spreadsheet, paired_spreadsheet):
    """Combines paired and individual spreadsheets to make a new spreadsheet.
    
       It does this by taking columns exclusive to paired bet spreadsheets and 
       merges to individual bets spreadsheets based on Profit ID."""
    
    for column in ['sport', 'Event', 'EventTime', 'datecreated ', 'BetType', 'Note']:
        partially_merged = pd.merge(individual_spreadsheet, 
                                    paired_spreadsheet.loc[:, ['ProfitID', column]], 
                                    on='ProfitID')
        individual_spreadsheet = partially_merged
        
    return individual_spreadsheet
        
bet_spreadsheet = merge_on_profit_id(individual_bets, paired_bets)

bet_spreadsheet.head(4)

,ProfitID,bookiename,BetOutcome,bettingtype,Outcome,stake,Odds,commission,liability,return,profit,sport,Event,EventTime,datecreated,BetType,Note
0,7967346,Coral,NaN,Back,Hungary,20.00,6.50,0,0.00,110.00,15.92,Football,Wales v Hungary,19/11/2019 19:45:00,19/11/2019 14:39:18,Free (SNR),NaN
1,7967346,Smarkets,NaN,Lay,Hungary,16.22,6.80,2,94.08,15.90,15.90,Football,Wales v Hungary,19/11/2019 19:45:00,19/11/2019 14:39:18,Free (SNR),NaN
2,7967454,Skybet,NaN,Back,North Macedonia,5.00,2.40,0,0.00,7.00,-0.33,Football,North Macedonia v Israel,19/11/2019 19:45:00,19/11/2019 14:56:02,Normal,NaN
3,7967454,Smarkets,NaN,Lay,North Macedonia,4.76,2.54,2,7.33,4.66,-0.34,Football,North Macedonia v Israel,19/11/2019 19:45:00,19/11/2019 14:56:02,Normal,NaN

The following functions are used to better organise and tidy up the newly combined spreadsheet.

In [23]:
def rename_colums(spreadsheet):
    """Renames columns on newly combined spreadsheet."""
    
    spreadsheet.columns = ['Profit ID', 'Bookie', 'Bet Result', 'Type', 
                               'Outcome', 'Stake','Odds', 'Fee (%)', 'Liability', 
                               'Return', 'Potential Profit', 'Sport', 'Event', 
                               'Event Time', 'Date Created', 'Bet Type', 'Note']
    
    return spreadsheet

bet_spreadsheet = rename_colums(bet_spreadsheet)

bet_spreadsheet.head(2)

,Profit ID,Bookie,Bet Result,Type,Outcome,Stake,Odds,Fee (%),Liability,Return,Potential Profit,Sport,Event,Event Time,Date Created,Bet Type,Note
0,7967346,Coral,NaN,Back,Hungary,20.00,6.5,0,0.00,110.0,15.92,Football,Wales v Hungary,19/11/2019 19:45:00,19/11/2019 14:39:18,Free (SNR),NaN
1,7967346,Smarkets,NaN,Lay,Hungary,16.22,6.8,2,94.08,15.9,15.90,Football,Wales v Hungary,19/11/2019 19:45:00,19/11/2019 14:39:18,Free (SNR),NaN

In [24]:
def reorder_columns(spreadsheet):
    """Reorders columns on newly combined spreadsheet."""
    
    columns_reordered = ['Date Created', 'Sport', 'Event', 'Event Time', 'Bookie',
                         'Bet Type','Type', 'Outcome', 'Stake', 'Odds', 'Fee (%)', 
                         'Liability', 'Return','Potential Profit', 'Bet Result',
                         'Note', 'Profit ID']
    
    spreadsheet = spreadsheet.loc[:, columns_reordered]
    
    return spreadsheet

bet_spreadsheet = reorder_columns(bet_spreadsheet)

bet_spreadsheet.head(2)

,Date Created,Sport,Event,Event Time,Bookie,Bet Type,Type,Outcome,Stake,Odds,Fee (%),Liability,Return,Potential Profit,Bet Result,Note,Profit ID
0,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Coral,Free (SNR),Back,Hungary,20.00,6.5,0,0.00,110.0,15.92,NaN,NaN,7967346
1,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Smarkets,Free (SNR),Lay,Hungary,16.22,6.8,2,94.08,15.9,15.90,NaN,NaN,7967346

In [25]:
def rename_type_normal(spreadsheet):
    """Renames to Bet Type 'Normal' to 'Qualifying' to better represent what the 
       bet does (qualify for free bet)."""
    
    spreadsheet.loc[:,'Bet Type'].replace('Normal', 'Qualifying', inplace=True)
    
    return spreadsheet

bet_spreadsheet = rename_type_normal(bet_spreadsheet)

bet_spreadsheet.head(4)

,Date Created,Sport,Event,Event Time,Bookie,Bet Type,Type,Outcome,Stake,Odds,Fee (%),Liability,Return,Potential Profit,Bet Result,Note,Profit ID
0,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Coral,Free (SNR),Back,Hungary,20.00,6.50,0,0.00,110.00,15.92,NaN,NaN,7967346
1,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Smarkets,Free (SNR),Lay,Hungary,16.22,6.80,2,94.08,15.90,15.90,NaN,NaN,7967346
2,19/11/2019 14:56:02,Football,North Macedonia v Israel,19/11/2019 19:45:00,Skybet,Qualifying,Back,North Macedonia,5.00,2.40,0,0.00,7.00,-0.33,NaN,NaN,7967454
3,19/11/2019 14:56:02,Football,North Macedonia v Israel,19/11/2019 19:45:00,Smarkets,Qualifying,Lay,North Macedonia,4.76,2.54,2,7.33,4.66,-0.34,NaN,NaN,7967454

In [26]:
def fill_note_NaN(spreadsheet):
    """Replace NaNs in notes with blank space."""
    
    spreadsheet.loc[:, 'Note'].fillna(' ', inplace=True)
    
    return spreadsheet

bet_spreadsheet = fill_note_NaN(bet_spreadsheet)

bet_spreadsheet.head(2)

,Date Created,Sport,Event,Event Time,Bookie,Bet Type,Type,Outcome,Stake,Odds,Fee (%),Liability,Return,Potential Profit,Bet Result,Note,Profit ID
0,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Coral,Free (SNR),Back,Hungary,20.00,6.5,0,0.00,110.0,15.92,NaN,,7967346
1,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Smarkets,Free (SNR),Lay,Hungary,16.22,6.8,2,94.08,15.9,15.90,NaN,,7967346

In [27]:
def win_lose_indices(winning_indices_list):
    """Input a list of indices of winning bets.
       Returns a tuple (list 1, list2, list3).
    
       list 1: indices of winning bets
       list 2: indices of subsequent losing bets
       list 3: indices of winning and losing bets
       
       If the smallest winning index is odd, then its paired bet (the preceeding index), 
       will be that of a losing bet and must be included in the losing index list.
       
       If the largest winning index is even, then its paired bet (the proceeding index), 
       will be that of a losing bet and must be included in the losing index list."""
    
    if min(winning_indices_list) % 2 == 0:
        range_min = min(winning_indices_list)
    else:
        range_min = min(winning_indices_list) - 1
    
    if max(winning_indices_list) % 2 == 0:
        range_max = max(winning_indices_list) + 2
    else:
        range_max = max(winning_indices_list) + 1
    
    bets_to_be_updated = range(range_min, range_max)
    losing_indices_list = list(set(bets_to_be_updated) - set(winning_indices_list))
    
    return (winning_indices_list, losing_indices_list, list(bets_to_be_updated))

# range_min odd, range_max odd
test_1 = win_lose_indices([1,2,5,6,9,10,13,15])
print("Test 1\n{}\n{}\n{}\n".format(test_1[0], test_1[1], test_1[2]))

# range_min odd, range_max even
test_2 = win_lose_indices([1,2,5,6,9,10,13,16])
print("Test 2\n{}\n{}\n{}\n".format(test_2[0], test_2[1], test_2[2]))

# range_min even, range_max odd
test_3 = win_lose_indices([0,2,5,6,9,10,13,15])
print("Test 3\n{}\n{}\n{}\n".format(test_3[0], test_3[1], test_3[2]))

# range_min even, range_max even
test_4 = win_lose_indices([0,2,5,6,9,10,13,16])
print("Test 4\n{}\n{}\n{}\n".format(test_4[0], test_4[1], test_4[2]))

Test 1
[1, 2, 5, 6, 9, 10, 13, 15]
[0, 3, 4, 7, 8, 11, 12, 14]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Test 2
[1, 2, 5, 6, 9, 10, 13, 16]
[0, 3, 4, 7, 8, 11, 12, 14, 15, 17]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

Test 3
[0, 2, 5, 6, 9, 10, 13, 15]
[1, 3, 4, 7, 8, 11, 12, 14]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Test 4
[0, 2, 5, 6, 9, 10, 13, 16]
[1, 3, 4, 7, 8, 11, 12, 14, 15, 17]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [28]:
def update_bet_results(spreadsheet, winning_indices_list):
    """Updates the spreadsheet with which bets won and lost."""
    
    win_lose_tuple = win_lose_indices(winning_indices_list)

    spreadsheet.loc[win_lose_tuple[0], 'Bet Result'] = "Win"
    spreadsheet.loc[win_lose_tuple[1], "Bet Result"] = "Lose"
    
    return spreadsheet

bet_spreadsheet = update_bet_results(bet_spreadsheet, [0,2,5,6,9,10,13,15])

bet_spreadsheet

,Date Created,Sport,Event,Event Time,Bookie,Bet Type,Type,Outcome,Stake,Odds,Fee (%),Liability,Return,Potential Profit,Bet Result,Note,Profit ID
0,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Coral,Free (SNR),Back,Hungary,20.00,6.50,0,0.00,110.00,15.92,Win,,7967346
1,19/11/2019 14:39:18,Football,Wales v Hungary,19/11/2019 19:45:00,Smarkets,Free (SNR),Lay,Hungary,16.22,6.80,2,94.08,15.90,15.90,Lose,,7967346
2,19/11/2019 14:56:02,Football,North Macedonia v Israel,19/11/2019 19:45:00,Skybet,Qualifying,Back,North Macedonia,5.00,2.40,0,0.00,7.00,-0.33,Win,,7967454
3,19/11/2019 14:56:02,Football,North Macedonia v Israel,19/11/2019 19:45:00,Smarkets,Qualifying,Lay,North Macedonia,4.76,2.54,2,7.33,4.66,-0.34,Lose,,7967454
4,20/11/2019 14:13:10,Football,Lincoln v Ipswich,20/11/2019 19:45:00,Skybet,Free (SNR),Back,1-2,20.00,11.00,0,0.00,200.00,15.08,Lose,,7975857
5,20/11/2019 14:13:10,Football,Lincoln v Ipswich,20/11/2019 19:45:00,Smarkets,Free (SNR),Lay,1-2,15.41,13.00,2,184.92,15.10,15.10,Win,,7975857
6,20/11/2019 22:11:55,Football,Levante v Mallorca,22/11/2019 20:00:00,William Hill,Qualifying,Back,Levante,10.00,1.85,0,0.00,8.50,-0.36,Win,,7979780
7,20/11/2019 22:11:55,Football,Levante v Mallorca,22/11/2019 20:00:00,Smarkets,Qualifying,Lay,Levante,9.84,1.90,2,8.86,9.64,-0.36,Lose,,7979780
8,20/11/2019 22:20:56,Horse Racing,Market Rasen 14:05,21/11/2019 14:05:00,William Hill,Free (SNR),Back,Buster Valentine,30.00,6.00,0,0.00,150.00,22.32,Lose,"odds changed in smarkets, liability was 118,\n...",7979843
9,20/11/2019 22:20:56,Horse Racing,Market Rasen 14:05,21/11/2019 14:05:00,Smarkets,Free (SNR),Lay,Buster Valentine,22.80,6.60,2,127.68,22.34,22.34,Win,"odds changed in smarkets, liability was 118,\n...",7979843
10,21/11/2019 21:24:34,Football,Levante v Mallorca,22/11/2019 20:00:00,BetWay,Qualifying,Back,Levante,30.00,1.87,0,0.00,26.10,-1.07,Win,,7987409
11,21/11/2019 21:24:34,Football,Levante v Mallorca,22/11/2019 20:00:00,Smarkets,Qualifying,Lay,Levante,29.53,1.92,2,27.17,28.94,-1.06,Lose,,7987409
12,22/11/2019 22:16:02,Football,West Ham v Tottenham,23/11/2019 12:30:00,BetWay,Free (SNR),Back,Draw,30.00,4.20,0,0.00,96.00,21.47,Lose,,7998004
13,22/11/2019 22:16:02,Football,West Ham v Tottenham,23/11/2019 12:30:00,Smarkets,Free (SNR),Lay,Draw,21.92,4.40,2,74.53,21.48,21.48,Win,,7998004
14,24/11/2019 09:55:09,Football,Sheff Utd v Man Utd,24/11/2019 16:30:00,Betfred,Free (SNR),Back,1-1,30.00,6.50,0,0.00,165.00,21.32,Lose,,8018379
15,24/11/2019 09:55:09,Football,Sheff Utd v Man Utd,24/11/2019 16:30:00,Smarkets,Free (SNR),Lay,1-1,21.77,7.60,2,143.68,21.33,21.33,Win,,8018379